import careerPage from "../../support/pages/careerPage"
const data = require("../../fixtures/data.json")

describe('Contact', () => {
  beforeEach(() => {
    cy.visit('')
    cy.url().should('contain', 'javan')
  })
  
  it('Upload with filesize 2MB', () => {
    careerPage.clickMenuCareer()
    cy.url().should('contain', 'career')
    careerPage.searchJob()
    careerPage.clickSearchButton()
    careerPage.clickApplyButton()
    cy.url().should('contain', data.job)
    careerPage.clickApplyNowButton()
    careerPage.inputFullName()
    careerPage.inputEmail()
    careerPage.inputPhone()
    careerPage.inputCompany()
    careerPage.clickBirthDay()
    careerPage.selectGender()
    careerPage.selectEducation()
    careerPage.inputUniv()
    careerPage.selectJoinDate()
    careerPage.selectWorking()
    careerPage.inputCurrentAddress()
    careerPage.inputAbout()
    careerPage.inputPorto()
    careerPage.inputLinkedin()
    careerPage.selectSource()
    careerPage.selectSmoke()
    careerPage.uploadFile2MB()
    careerPage.clickButtonApplyJob()
    careerPage.verifySuccessSubmit()
  })

  it('JVN-005 Upload with filesize 5MB', () => {
    careerPage.clickMenuCareer()
    cy.url().should('contain', 'career')
    careerPage.searchJob()
    careerPage.clickSearchButton()
    careerPage.clickApplyButton()
    cy.url().should('contain', data.job)
    careerPage.clickApplyNowButton()
    careerPage.inputFullName()
    careerPage.inputEmail()
    careerPage.inputPhone()
    careerPage.inputCompany()
    careerPage.clickBirthDay()
    careerPage.selectGender()
    careerPage.selectEducation()
    careerPage.inputUniv()
    careerPage.selectJoinDate()
    careerPage.selectWorking()
    careerPage.inputCurrentAddress()
    careerPage.inputAbout()
    careerPage.inputPorto()
    careerPage.inputLinkedin()
    careerPage.selectSource()
    careerPage.selectSmoke()
    careerPage.uploadFile5MB()
    careerPage.clickButtonApplyJob()
    careerPage.verifySuccessSubmit()
  })

  it('JVN-004 Upload with filesize 9MB', () => {
    careerPage.clickMenuCareer()
    cy.url().should('contain', 'career')
    careerPage.searchJob()
    careerPage.clickSearchButton()
    careerPage.clickApplyButton()
    cy.url().should('contain', data.job)
    careerPage.clickApplyNowButton()
    careerPage.inputFullName()
    careerPage.inputEmail()
    careerPage.inputPhone()
    careerPage.inputCompany()
    careerPage.clickBirthDay()
    careerPage.selectGender()
    careerPage.selectEducation()
    careerPage.inputUniv()
    careerPage.selectJoinDate()
    careerPage.selectWorking()
    careerPage.inputCurrentAddress()
    careerPage.inputAbout()
    careerPage.inputPorto()
    careerPage.inputLinkedin()
    careerPage.selectSource()
    careerPage.selectSmoke()
    careerPage.uploadFile9MB()
    careerPage.clickButtonApplyJob()
    careerPage.verifySuccessSubmit()
  })
  
})